# -*- coding: utf-8 -*-
"""Used_car_price

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X18PddYZRRQnAs1t_wQIwoppdnrT1NCY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("09_used_car_price.csv")
df.head()

# Shape of the dataset
print("Shape:", df.shape)

# Column names
print("\nColumns:", df.columns.tolist())

# Data types of each column
print("\nData types:\n", df.dtypes)

# Basic statistics for numerical columns
df.describe()

# Count missing values per column
print(df.isnull().sum())

# Percentage of missing values per column
print("\nPercentage missing:\n", (df.isnull().sum() / len(df)) * 100)

# Count of fully duplicated rows
print("Number of duplicate rows:", df.duplicated().sum())

# View the actual duplicate rows (if any)
df[df.duplicated()]

# 1. Negative car age
print("Negative car_age_years:\n", df[df['car_age_years'] < 0])

# 2. Negative kilometers driven
print("\nNegative km_driven:\n", df[df['km_driven'] < 0])

# 3. Unrealistic owner counts
print("\nUnrealistic owners:\n", df[df['owners'] > 5])

# 4. Negative or zero price
print("\nNegative/zero price_lakh:\n", df[df['price_lakh'] <= 0])

# Histograms for car_age_years and km_driven
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

sns.histplot(df['car_age_years'], bins=20, ax=axes[0], kde=True)
axes[0].set_title('Distribution of Car Age (years)')

sns.histplot(df['km_driven'], bins=20, ax=axes[1], kde=True)
axes[1].set_title('Distribution of KM Driven')

plt.tight_layout()
plt.show()

# Boxplots to spot outliers
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

sns.boxplot(y=df['car_age_years'], ax=axes[0])
axes[0].set_title('Boxplot: Car Age (years)')

sns.boxplot(y=df['km_driven'], ax=axes[1])
axes[1].set_title('Boxplot: KM Driven')

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

sns.scatterplot(x=df['car_age_years'], y=df['price_lakh'], ax=axes[0])
axes[0].set_title('Car Age vs Price')

sns.scatterplot(x=df['km_driven'], y=df['price_lakh'], ax=axes[1])
axes[1].set_title('KM Driven vs Price')

sns.scatterplot(x=df['engine_cc'], y=df['price_lakh'], ax=axes[2])
axes[2].set_title('Engine Size vs Price')

plt.tight_layout()
plt.show()

# Select only numeric columns and compute correlation
corr_matrix = df.corr(numeric_only=True)

# Plot heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

df = df.drop_duplicates()
print("Shape after removing duplicates:", df.shape)

df = df[df['car_age_years'] >= 0]
print("Shape after removing negative car_age_years:", df.shape)

df = df[df['km_driven'] >= 0]
print("Shape after removing negative km_driven:", df.shape)

df = df[df['owners'] <= 5]
print("Shape after removing unrealistic owners:", df.shape)

df = df[df['price_lakh'] > 0]
print("Shape after removing invalid price_lakh:", df.shape)

# Fill missing values with median for numeric column
for col in ['car_age_years', 'km_driven', 'engine_cc', 'owners']:
    df[col] = df[col].fillna(df[col].median())

# Confirm no missing values remain
print(df.isnull().sum())

# Avoid division by zero: add 1 to car_age_years for cars with age 0
df['km_per_year'] = df['km_driven'] / (df['car_age_years'] + 1)

df[['car_age_years', 'km_driven', 'km_per_year']].head()

# Flag cars with above-median km_driven as "high mileage"
median_km = df['km_driven'].median()
df['is_high_mileage'] = (df['km_driven'] > median_km).astype(int)

df[['km_driven', 'is_high_mileage']].head()

# Final sanity checks
print("Shape:", df.shape)
print("\nMissing values:\n", df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())
print("\nSummary statistics:\n", df.describe())

# X = all features except the target
X = df.drop('price_lakh', axis=1)

# y = the target variable
y = df['price_lakh']

print("X shape:", X.shape)
print("y shape:", y.shape)
X.head()

"""## Conclusion

This project involved performing exploratory data analysis (EDA) and feature
engineering on a used car price dataset containing 1000 records.

**Data Quality Issues Found:**
- 20 duplicate rows
- Missing values in car_age_years, km_driven, engine_cc, and owners (~1% each)
- 5 rows with invalid negative car ages
- 5 rows with invalid negative kilometers driven (-10000)
- 5 rows with unrealistic owner counts (8 owners)
- 20 rows with negative or zero prices

After cleaning, the dataset was reduced from 1000 to 938 valid records.

**Key Insights:**
- **car_age_years** showed the strongest relationship with price (correlation: -0.67)
  — older cars sell for significantly less.
- **km_driven** was the second most important factor (correlation: -0.54)
  — higher mileage strongly reduces resale value.
- **engine_cc** had a weak positive correlation with price (0.13), suggesting
  engine size alone isn't a strong price predictor in this dataset.
- **owners** showed almost no correlation with price (-0.01).

**Features Engineered:**
- `km_per_year`: normalizes mileage by car age, giving a more meaningful usage metric
- `is_high_mileage`: a binary flag indicating whether a car has above-median mileage

**Takeaway:** Car age and mileage are the dominant drivers of resale price for this
dataset, while engine size and ownership history play a minor role. This aligns with
common intuition about used car valuation.
"""